[workspace]
members = ["crates/*"]
exclude = ["src/tests/mock_project", "crates/salt/test-crate", "test-project"]
resolver = "2"

[workspace.dependencies]
rustc_plugin = "0.11.0-nightly-2024-12-01"
rustc_utils = "0.11.0-nightly-2024-12-01"